---
# SPDX-FileCopyrightText: 2026  IMAGIN sp. z o.o.
# SPDX-FileContributor: Marcin Engelmann <mengelmann@octivi.com>
# SPDX-License-Identifier: MIT
#
# This file is part of the configuration created by Octivi's DevOps team.
# Details at https://octivi.com/devops
name: Prettify code

on:
  push:
    branches:
      - "**"
    paths:
      - "**/*.md"
    # Don't run when someone pushes just tags
    tags-ignore:
      - "**"
  pull_request:
    paths:
      - "**/*.md"
  workflow_dispatch:

jobs:
  prettier-check:
    if: github.event_name == 'pull_request'
    name: Prettier (check)
    runs-on: ubuntu-slim
    permissions:
      contents: read
    steps:
      - name: Check out repository code
        uses: actions/checkout@v6

      - name: Run Prettier (check)
        uses: creyD/prettier_action@v4.6
        with:
          prettier_options: --check **/*.md

  prettier-write:
    if: github.event_name != 'pull_request'
    name: Prettier (write)
    runs-on: ubuntu-slim
    permissions:
      contents: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v6

      - name: Run Prettier (write)
        uses: creyD/prettier_action@v4.6
        with:
          prettier_options: --write **/*.md
          commit_message: "chore: prettify code with Prettier"
